services:
  - docker

install:
  - docker pull josswhittle/opt-id:env-v3

script:
  - docker run josswhittle/opt-id:env-v3 python -m pytest tests/*

# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     branch: master
